accounts/urls.py
urlpatterns = [
    
]

askcompany/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('', RedirectView.as_view(
        #url='/instagram/'
        pattern_name='instagram:post_list'
    ), name='root'),
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog1/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.post_list, name='post_list'),
]

instagram/urls.py
from django.urls import re_path, path, register_converter


from . import views

class YearConverter:
    regex = r"20\d{2}"

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return str(value)

register_converter(YearConverter, "year")

app_name = "instagram"      # URL Reverse에서 namespace 역할을 맞게 된다

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),    # 포스트(게시판목록의 상세) 내용 확인하는 url
    #re_path(r'(?P<pk>\d+)/$', views.post_detail),
    #path('archives/<int:year>', views.archives_year)
    #re_path(r'archives/(?P<year>\d+)/', views.archives_year),
    path('archives/<year:year>/', views.archives_year),
    
    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_year'),
]

accounts/models.py
from django.conf import settings
from django.conf import settings
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=6) #, validators=[]
        

blog1/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
# SQL 모델 생성 구성
#   python manage.py makemigrations [AppName]
#   python manage.py migrate [AppName]
#       * 정방향이란? 
#           - 원래 순서대로의 모델 클래스 구성 및 테이블 구현
#       * 역방향도 존재!
#           - 역방향은 정방향의 반대로 이전 버전의 테이블 구조 및 스키마로 되돌아간다. (Un-do)
#           - python manage.py migrate [AppName] [Migration-Name]
#       * 마이그레이션 이름 지정 
#           - 전체 이름(파일명)을 지정하지 않더라도, 1개를 판별할 수 있는 일부만 지정해도 판단하에 진행된다.
#           - ex) python manage.py migrate blog 000     # Fail (기본적으로 일치하는 값들 여러개 있을 경우)
#                 python manage.py migrate blog 0001    # OK
#   migrate 되지 않은 건에 대해서는 삭제를 진행해도 되지만, 그 외에는 삭제처리를 하지 않는 것이 좋다.
#
#   Tip
#       - 하나의 커밋에 대해 하나의 마이그레이션 적용하는 것을 권장
#       - 개발자 각 각의 마이그레이션 진행하지 않고 대표 1인이 마이그레이션 하는 것을 권장

instagram/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                               related_name='+')
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Java, .Net ToString()
    def __str__(self):
        #return "Custom Post object ({})".format(self.id)
        #return f"Cutom Post object ({self.id})" # Python 3.7 이후
        return self.message
  
    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])
    
    
    class Meta:
        ordering =  ['-id']
    
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메시지 글자수"
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             limit_choices_to={'is_public': True},) # post_id 필드가 생성
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
        pass
    

instagram/forms.py
from dataclasses import field
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog1/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def post_list(request):
    qs = Post.objects.all()
    return render(request, 'blog1/post_list.html', {        
        'post_list': qs,
    })

instagram/views.py
from atexit import register
from http.client import HTTPResponse
from pyexpat import model
from django.forms import DateField
from django.http import Http404, HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import register_converter
from django.utils.decorators import method_decorator
from django.core.checks import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView
from .models import Post
from .forms import PostForm

#post_list = ListView.as_view(model=Post, paginate_by=10)

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm()
    
    return render(request, 'instagram/post_form.html', {
        'form': form
    })

@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
      model = Post
      paginate_by = 100

post_list = PostListView.as_view()

# Create your views here.
# @login_required
# def post_list(request):
#     qs = Post.objects.all()
    
#     q = request.GET.get('q','')
#     if q:
#         qs = qs.filter(message__icontains=q)
#     # instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q
#     })

    
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    response = HttpResponse()
    response.write("Hellow World")
    response.write("Hellow World")
    response.write("Hellow World")
    return response

def archives_year(request, year):
    return HttpResponse(f"{year}년 achives")
# post_detail = DetailView.as_view(model=Post,
#                                  queryset=Post.objects.filter(is_public=True))   

class PostDetailView(DetailView):
    model = Post
  # queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)        
        return qs

post_detail = PostDetailView.as_view()

# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)
#     #try:
#     #    post = Post.objects.get(pk=pk)  # Post.DoesNotExists 예외
#     #except:
#     #    raise Http404
#     return render(request, 'instagram/post_detail.html', {
#         'post': post
#     })

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)
post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

askcompany/templates/root.html
Instagram with Django/React.

blog1/templates/blog1/post_list.html
<h1>Post List</h1>

<ul>
{% for post in post_list %}
   <h2>{{ post.title }}</h2> 
   {{ post.content }}
{% endfor %}
</ul>

instagram/templates/instagram/layout.html
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- CSS only -->
        {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/litera/bootstrap.min.css" integrity="sha384-enpDwFISL6M3ZGZ50Tjo8m65q06uLVnyvkFO3rsoW0UC15ATBFz3QEhr3hmxpYsn" crossorigin="anonymous"> {% endcomment %}
        {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/superhero/bootstrap.min.css" integrity="sha384-HnTY+mLT0stQlOwD3wcAzSVAZbrBp141qwfR4WfTqVQKSgmcgzk+oP0ieIyrxiFO" crossorigin="anonymous"> {% endcomment %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/simplex/bootstrap.min.css" integrity="sha384-FYrl2Nk72fpV6+l3Bymt1zZhnQFK75ipDqPXK0sOR0f/zeOSZ45/tKlsKucQyjSp" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <style>
            body {
                padding-top: 5rem;
                padding-bottom: 2rem;
            }
        </style>
    </head>
    <body>     
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Fixed navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>  
          <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    {% block content %}
                    {% endblock content %}

                    <hr/>
                    &copy; Ask Company.
                </div>
            </div>
          </div>        
    </body>
</html>

instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2>date_list</h2>

{% for date in date_list %}
    {{ date|date:"Y" }}
    {{ date.year }}
{% endfor %}

instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{ year }}
<h2>previous_year</h2>
{{ previous_year }}
<h2>next_year</h2>
{{ next_year }}
<h2>date_list</h2>
{{ date_list }}
<h2>object_list</h2>
{{ object_list }}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}


{% block title %}
    Post Detail pk#{{post.pk}}
{% endblock title %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

    {% if post.photo %}
    <div>
        <img src="{{ post.photo.url }}" />
    </div>
    {% endif %}

    {{ post.message }}
    <hr />
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>
{% endblock content %}

instagram/templates/instagram/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="저장" />
</form>

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}
{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>

    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">새 포스팅</a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
            <tr>
                <td>{{ post.pk }}</td>
                <td>
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" style="width: 100px;" />
                    {% else %}
                        No Photo
                    {% endif%}
                </td>
                <td>
                    {% comment %} <a href="{% url 'instagram:post_detail' post.pk %}"> {% endcomment %}
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.message }}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}
{% endblock content %}